### ISSUE TITLE
Dask-SQL not wrapping partition value in quotes

### ISSUE THREAD

**Issue by gallamine** [dask-contrib/dask-sql#179]
Hello, I am querying a Hive table that is partitioned using string values that look like a date -`YYYY-MM-DD`. My `create_table` command fails with a `HiveSQLException` because the `-` isn't being escaped.
For example:

```
[SQL: DESCRIBE FORMATTED schema.table PARTITION (partition_col=2019-01-21)]
```

this should instead read `partition_col="2019-01-21"`.

I am using `dask-sql==0.3.6`

**Comment by nils-braun** [comment]
Thanks for the bug report @gallamine - that definitely is a bug.
I think all that we would need to fix is [this SQL string](https://github.com/nils-braun/dask-sql/blob/main/dask_sql/input_utils/hive.py#L177) to also include proper escaping. 
Would you like to do a PR, as you have already the Hive data available for testing?
You can follow the description [here](https://dask-sql.readthedocs.io/en/latest/pages/installation.html#for-development) for how to setup dask-sql in development. I would love to see your PR!

**Comment by gallamine** [comment]
@nils-braun I'm interested. Trying to think of an elegant way of knowing whether the partition value should be enclosed in quotations or not. Is there a good way you know of for determining what the type of `partition_col` is?

**Comment by nils-braun** [comment]
Hi @Robert-Christensen-visa , @gallamine - that would be very nice and would simplify our lives a lot!

Sorry @gallamine for not continuing the discussion on the PRs and here. Can we pick this up again?
