### ISSUE TITLE
Consider using default sorting algorithm with `partition.sort_values` function

### ISSUE THREAD

**Issue by sarahyurick** [dask-contrib/dask-sql#204]
Hi, I was wondering if there is a reason behind `kind="mergesort"` being used in [sort.py](https://github.com/nils-braun/dask-sql/blob/c9ce6de09fb27ed67e2454bbc02b9532125795d7/dask_sql/physical/utils/sort.py): 
```
        partition = partition.sort_values(
            by=[col], ascending=asc, na_position=na_position, kind="mergesort"
        )
```
instead of not specifying the `kind` parameter and using the [default](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html) quicksort? There also does not appear to be a way to override this.

**Comment by nils-braun** [comment]
Hi @sarahyurick - thanks for your question! Yes, there was a reason behind this indeed. It is described a few lines [above the code you pasted](https://github.com/nils-braun/dask-sql/blob/c9ce6de09fb27ed67e2454bbc02b9532125795d7/dask_sql/physical/utils/sort.py#L50) and is basically a speed improvement when we have multiple columns (referencing [this pandas issue](https://github.com/pandas-dev/pandas/issues/17111)).
Do you see any performance degrading? I would be very interested to learn about that!

**Comment by sarahyurick** [comment]
Thanks for the response! I was mostly just curious - I haven't compared Pandas' mergesort versus quicksort performance before.
