### ISSUE TITLE
Move to dask-contrib

### ISSUE THREAD

**Issue by jacobtomlinson** [dask-contrib/dask-sql#210]
A while back in dask/community#115 there was some interest shown in moving this project over to the [dask-contrib org](https://github.com/dask-contrib/). I would be really excited to see this happen!

I think the road to this would be for @nils-braun to transfer ownership of this project to any of the Dask owners and then we can move it into the contrib org. Perhaps either myself, @jsignell or @jrbourbeau would be good candidates to perform the migration.

Once it is migrated we can ensure that @nils-braun still has full ownership of the repo.

@nils-braun are you happy to make this happen?

**Comment by nils-braun** [comment]
I would be very happy to do so. Thanks you do asking. I will do so this evening. 

Is there anything I need to change in the repository (like Contribution information, license or alike?).

**Comment by jacobtomlinson** [comment]
Awesome! If you're going to do it during the Europe evening you may want to coordinate with @jrbourbeau or @jsignell via the Dask Slack for a smooth transfer as they will be around.

**Comment by jacobtomlinson** [comment]
It's MIT now so I expect that till be fine.

**Comment by jrbourbeau** [comment]
+1 @nils-braun and I are coordinating now

**Comment by nils-braun** [comment]
The repository is successfully transferred: https://github.com/dask-contrib/dask-sql
Thanks to @jrbourbeau and @jacobtomlinson for your help!

**Comment by mrocklin** [comment]
Woo!

**Comment by jsignell** [comment]
Welcome!

**Comment by jacobtomlinson** [comment]
Woop!
