### ISSUE TITLE
Docs link broken in the `about` section of the github repo

### ISSUE THREAD

**Issue by rajagurunath** [dask-contrib/dask-sql#212]
In the About section of the repo the link https://nils-braun.github.io/dask-sql/ seems broken shall we change the link to 
https://dask-sql.readthedocs.io/en/latest/  or any other idea?

**Comment by nils-braun** [comment]
Oh, good point! I totally forgot that this URL also changed during the move to dask-contrib. It's now under dask-contrib.github.io/dask-sql. I will change the URL. We should make a pass over the full repo do fix all old links (repo + website) at some point.
