### ISSUE TITLE
[Docs] API docs not rendering on docs site

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#215]
The api documentations [page](https://dask-sql.readthedocs.io/en/latest/pages/api.html) returns a blank page on the docs site.

**Comment by nils-braun** [comment]
Thanks @ayushdg - there seems to be a bug in the sphinx build process.
Until it's fixes, please have a look into [an older version](https://dask-sql.readthedocs.io/en/0.3.6/pages/api.html).

**Comment by nils-braun** [comment]
The problem is fixed now and the [API docs](https://dask-sql.readthedocs.io/en/latest/pages/api.html) are visible again. There was a dependency missing during the sphinx build process.
Why I did not receive a mail due to the failed build from readthedocs I do not know so far...

**Comment by ayushdg** [comment]
Thanks @nils-braun for the quick response and fix!
