### ISSUE TITLE
Row-wise scalar UDFs

### ISSUE THREAD

**Issue by brandon-b-miller** [dask-contrib/dask-sql#225]
Hello, first off thanks for `dask-sql`!

I noticed (and please correct me if I am wrong) that the current process for running UDFs basically works by forwarding the relevant columns of a table directly to that python function as arguments. That is, if I have

```python
def f(x, y):
    return x + y
```

and I write

```
"SELECT f(col0, col1) FROM my_table"
```
The impl will pass `col0` and `col1` as dask series directly as arguments to `f`, at which point `f` simply runs a binop between those two actual series objects and returns a new series as a result. This implementation works great but has some limitations in the space of functions that a user can define when compared to a "row-wise" UDF. For instance one cannot write functions of this form:

```
def f(x, y):
    if x > 3: # here, type(x) is <class 'dask.dataframe.core.Series'>
        return y
    else:
        return x + 4

# ValueError: The truth value of a Series is ambiguous. Use a.any() or a.all().
```

I was wondering if there were any thoughts/plans around supporting true row-wise ops, where within the partitions each row is individually sent through the UDF as a set of scalars. Perhaps such an implementation could leverage `pd.DataFrame.apply` or similar.

Thanks!

**Comment by brandon-b-miller** [comment]
Thank you both for your detailed replies. 

Allow me to address the performance consideration first as I think it constitutes a stronger motivation. Indeed, pandas does not make many performance promises when it comes to row wise UDFs that behave in this manner. However I believe part of what makes dask great in general is that it focuses on being a really great engine for distributing computation - and it tends to leave what happens within the partitions up to the "backend" library (pandas, cuDF), so long as it implements the right API. From that perspective I do not believe the onus should be on dask to protect the user from workflows that are slow because the pandas `apply` api is slow. `cuDF`'s `apply` function uses numba to jit cuda kernels which are relatively performant for example, even when compared to the logical equivalent using GPU arrays (`x=a+b+c+d+e` might be faster using `apply` than passing the vectors themselves, which will resolve in python to 4 separate binops I believe)

By the way, thanks for the numpy example - I learned something I did not know before. Certainly it would seem that recasting ones UDF in the language of such array operations can support a broad spectrum of logical cases. That said I postulate that users (especially newer ones from python in general) have an easier time prototyping/implementing scalar functions where all the objects inside that function behave like simple python scalars/objects that seem easy and familiar. As the logic becomes more complicated I suspect this effect will be more pronounced. Eventually, especially when strings and other dtypes enter the mix, UDFs will probably come along that cant be dask-ified in this way. 

If you are open to my experimenting with this I am happy to probe what would be required, or if this still seems like something it would be better not to support I can consider some alternatives - either way, thank you again for the discussion.

**Comment by nils-braun** [comment]
Oh! I wasn't aware that `cuDF` does already optimize the `apply`s. Well, that makes things less in-performant then :-)

I am with you that this will probably increase usability, especially for new users. Probably that is something we should optimize for. I am just still a bit scared that we make it too easy to do it wrong (because I still assume that many users will have a pandas backend).

How about the following: I am happy if you would like to go ahead and find some convenient way to create those functions. When we add this to the documentation, we make sure that we have some big warning sign :-) In this case, I am also happy.

**Comment by brandon-b-miller** [comment]
Picking up work on this shortly and hopefully a PR to come :)
