### ISSUE TITLE
Strategy for running CI-tests against GPU machines

### ISSUE THREAD

**Issue by nils-braun** [dask-contrib/dask-sql#227]
With the recent integration of dask-cudf into dask-sql, it would be wise to start testing against GPU libraries and machines in the automated build triggered by GitHub actions.

@ayushdg mentioned on [#220](https://github.com/dask-contrib/dask-sql/issues/220#issuecomment-904761024_), that:
> GpuCI is one option that could be used to test integration with rapids libraries. It's what the dask repository uses as well (https://github.com/dask/community/issues/138).
> I don't think it uses GitHub actions specifically but is enabled via a webhook to GitHub.

I would be very much interested, if this is also an option for dask-contrib packages (and if this would be supported by RAPIDS) and what the current experience with the setup at the dask main repository is. Maybe, @quasiben, @jrbourbeau, can you shortly summarize the current setup in the dask main repository and how the experiences are? Thanks!

**Comment by charlesbluca** [comment]
The basic setup for Dask's gpuCI consisted of:

- Marking relevant GPU tests with a custom pytest marker (see dask/dask#7876)
- Enabling gpuCI on a fork of Dask and getting the required setup files working there (see charlesbluca/dask#1); these files consist of
  - a [shell script](https://github.com/dask/dask/blob/main/continuous_integration/gpuci/build.sh) defining the steps to build the test environment and run the desired tests
  - a [YAML file](https://github.com/dask/dask/blob/main/continuous_integration/gpuci/axis.yaml) defining the build matrix
- Once gpuCI works in the forked branch, merging this branch into the main repo and enabling gpuCI there

Once enabled, gpuCI runs on all PRs opened by members on an allowlist (in Dask's case, this contains all members of the organization as well as some other people added using the commands listed [here](https://docs.dask.org/en/latest/develop.html#gpu-ci)); initially, there was some noisiness as the gpuCI bot pinged a large chunk of the open Dask PRs for approval to run GPU tests, but this should be avoidable here if we populate the allowlist before enabling.

Another thing to consider is that gpuCI on Dask and Distributed uses Docker images (generated nightly based on specifications [here](https://github.com/rapidsai/dask-build-environment/)) to speed up the overall test time; we might want to do something similar for dask-sql, but I'm interested in if it would be possible to reuse one of those images here.
