### ISSUE TITLE
Who should have admin privileges for gpuCI?

### ISSUE THREAD

**Issue by charlesbluca** [dask-contrib/dask-sql#239]
As we move forward with getting gpuCI set up for dask-sql, we need to decide who will be on gpuCI's list of admins for this repo.

gpuCI admins have the ability to:

- Approve PRs from users not currently on gpuCI's list of approved users
- Add users to gpuCI's approved users list so all of their PRs will trigger gpuCI

A more detailed description of this can be found in [Dask's docs](https://docs.dask.org/en/latest/develop.html#gpu-ci).

For Dask and Distributed, the admin list is made up of the Dask org owners, as well as some RAPIDS folk involved heavily in Dask. For this repo, I'd imagine we would also want @nils-braun and @rajagurunath, along with some other people who have been actively doing GPU development here over the past few weeks.

Happy to get some feedback on this!

**Comment by jakirkham** [comment]
Thanks for writing this up Charles! 😄

Agree it would be good to here from Nils & Gurunath.

Thinking about how other CI services work for a moment, usually permissions are conveyed based on what permissions one has on the repo itself. Maybe this would make sense here? If so, one thing to unpick would be whether one needs `write` permissions on the repo or `admin` permissions on the repo.

**Comment by charlesbluca** [comment]
I think `write` permissions correspond pretty well with gpuCI admin privileges, in that [write access is required to approve workflow runs for first-time contributors](https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/).

Basing gpuCI permissions on repo permissions seems sensible, although since gpuCI permissions are handled independently from GitHub's, there's bound to be a lag between a user getting write access to the repo and them getting gpuCI admin permissions - in any case it's definitely a good place to start 🙂

**Comment by jakirkham** [comment]
Sure my guess is we will add a few people to start and then things will stay more-or-less the same for a while. So we can just take a look at who has `write` permissions once we are ready and add them. Should add would be happy to hear thoughts from Nils & Gurunath (and potentially do something different if they have preferences)

**Comment by rajagurunath** [comment]
First of all Thanks a lot for all the efforts integrating gpuCI to dask-sql  @charlesbluca @jakirkham 

Apologies for the delayed response here, As Discussed above, Since we can add any number of Users to the gpuCI approved list in the future (but understood the concern (gpuCI bot getting pinged multiple times) @charlesbluca  mentioned here https://github.com/dask-contrib/dask-sql/issues/227),  I also don't have a better suggestion at this point of time, maybe let start with the write permission for @nils-braun  and @rajagurunath  (myself, Thanks for nominating :) ). we will use `add to allow list` for the future users whoever wants to use gpuCI.  Any Other thoughts/ better plans?

Please let me know if I have missed any information, and also let me know how can I help towards integrating gpuCI to dask-sql.

**Comment by charlesbluca** [comment]
Sorry if I didn't make this clear with the original issue description - I'm more thinking of the list of users to make gpuCI *admins* (that is, can decide who is approved for GPU testing or not). The initial list of approved users will likely be much larger than the admin list - for example, in Dask/Distributed we started off by adding all members of the Dask org to the approved list, with admins adding any additional frequent contributors that may have been missed.

I'm personally not too concerned about the approved list, as like you said it's pretty easy to add on to with `add to allow list`, and we should be safe starting off with Dask/Distributed's list + a few obvious additions. The admin list I feel deserves a little more consideration as it is more difficult to add users to (requires RAPIDS ops approval).

**Comment by jakirkham** [comment]
We might want to add the admins from the Dask org to dask-contrib generally
