### ISSUE TITLE
[ENH] Support NULLS {FIRST | LAST} in ORDER BY grammar

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#288]
Postgresql supports specifying the NULLS ordering in the ORDER BY statement as described [here](https://www.postgresql.org/docs/8.3/queries-order.html) we should similarly support this functionality

**Comment by rajagurunath** [comment]
Hi @jdye64,

Thanks for Creating/Working on this issue!

A few days back I saw some `order by`  test cases in dask-sql (which seems working, except for some edge cases), Are we looking for something similar here? 🤔  

https://github.com/dask-contrib/dask-sql/blob/77f1d87ba7a3913d66afa8ceaf6b5e124bbf6644/tests/integration/test_compatibility.py#L145-L176

**Comment by jdye64** [comment]
Before closing this I want to add 1 more pytest just to ensure we are getting full grammar testing coverage. I will post that PR here once I do so. If that passes this can be closed.

**Comment by jdye64** [comment]
After looking at the pytest a little more the other 2 situations that I wanted to cover appear to already be covered. Therefore I'm going to close this general issue and we can open more specific ones if edge cases pop up.
