### ISSUE TITLE
[DOC] Discuss internal GPU support rather than referring to Blazing

### ISSUE THREAD

**Issue by vyasr** [dask-contrib/dask-sql#291]
## Report incorrect documentation

**Location of incorrect documentation**
The [Quickstart section of the README](https://github.com/dask-contrib/dask-sql#quickstart).

**Describe the problems or issues found in the documentation**
This section refers users wanting to use GPUs for queries to BlazingSQL.

**Steps taken to verify documentation is incorrect**
N/A

**Suggested fix for documentation**
This section should no longer refer to BlazingSQL and should instead talk about GPU support in Dask-SQL. I would make the change myself, but I'm not familiar enough with the project at this stage to know exactly what to say here.

**Comment by quasiben** [comment]
@ayushdg would you be up for fixing the README ?

**Comment by ayushdg** [comment]
Yeah, happy to make the change.
