### ISSUE TITLE
[QST] Transition to CalVer with next release?

### ISSUE THREAD

**Issue by charlesbluca** [dask-contrib/dask-sql#299]
**What is your question?**
In #257, I suggested maybe moving our versioning to CalVer to match up with Dask/Distributed - how do we feel about doing that with our next release? We may have another one coming soon, as it would be nice to have a stable version out with the JVM segfaults in #297 resolved.

I was thinking `YYYY.MM.MINOR` to mirror Dask/Distributed, not sure if we would want to zero-pad minor version (i.e. `00` instead of `0`) depending on how many patches we anticipate releasing between monthly releases.

cc @rajagurunath @quasiben @galipremsagar

**Comment by quasiben** [comment]
+1 to switching to CalVer

xref: https://github.com/dask/community/issues/100 for the larger discussion on the decision to switch

cc @goodwanghan for awareness

**Comment by charlesbluca** [comment]
This is done, we are now on `2021.11.0`
