### ISSUE TITLE
[ENH] Add tests for cuML+Dask-ML+dask-sql

### ISSUE THREAD

**Issue by VibhuJawa** [dask-contrib/dask-sql#309]
**Is your feature request related to a problem? Please describe.**

Once [PR](https://github.com/dask/dask-ml/pull/862) lands, We should add tests for cuML+DASK-ML+dask-sql  to ensure we have CI success there. 

We should also remove marked xfail tests marked in this PR https://github.com/dask-contrib/dask-sql/pull/304 

CC: @charlesbluca , @randerzander , @ChrisJar

**Comment by charlesbluca** [comment]
Is dask-ml planning a release shortly after this PR? We'll probably also need to bump our dependency version as well

**Comment by VibhuJawa** [comment]
> Is dask-ml planning a release shortly after this PR? We'll probably also need to bump our dependency version as well

I don't know how the `dask-ml` release cycle works to be honest but thanks will ensure that we update the dependency version as needed.

**Comment by charlesbluca** [comment]
Yup, just noticed and was actually just about to un-xfail the tests 😃 are you currently working on this? If not I can go ahead and open up my PR

**Comment by VibhuJawa** [comment]
> Yup, just noticed and was actually just about to un-xfail the tests 😃 are you currently working on this? If not I can go ahead and open up my PR

Please feel free to un-xfail your tests.    

I am working on adding some tests for cuML+Dask-SQL which are tangential to the tests marked in this [PR](https://github.com/dask-contrib/dask-sql/pull/304/files).

**Comment by VibhuJawa** [comment]
Closed by https://github.com/dask-contrib/dask-sql/pull/330
