### ISSUE TITLE
⚠️ Nightly upstream-dev CI failed ⚠️

### ISSUE THREAD

**Issue by charlesbluca** [dask-contrib/dask-sql#350]
Looks like the Dask upstream testing has started failing:

https://github.com/dask-contrib/dask-sql/actions/runs/1604667145

This should've triggered an issue to be opened automatically, but didn't; I can look into that later, but it seems to have something to do with these conditionals:

https://github.com/dask-contrib/dask-sql/blob/2e5cfcb59701ea7d35b146a32690a0315b7f82d8/.github/workflows/test-upstream.yml#L102-L106

https://github.com/dask-contrib/dask-sql/blob/2e5cfcb59701ea7d35b146a32690a0315b7f82d8/.github/workflows/test-upstream.yml#L116-L119

cc @quasiben @galipremsagar

**Comment by ayushdg** [comment]
Test failures seem to be ml related. I can look into this unless someone already is

**Comment by galipremsagar** [comment]
@ayushdg You can look into it. AFAIK no one else is looking into it.

**Comment by ayushdg** [comment]
Tracked this down to failures in dask/dask-ml#895 post the merge of dask/dask#8452.

**Comment by ayushdg** [comment]
This should now be fixed since dask/dask-ml#898 merged. @charlesbluca Would it be possible to trigger a run with upstream dask and dask-ml to see if the issue is resolved on our end?

**Comment by charlesbluca** [comment]
Currently our upstream testing only uses latest Dask, but I can modify it to also use latest dask-ml and then run a test manually.

**Comment by charlesbluca** [comment]
Tested with the latest dask / dask-ml in this [run](https://github.com/dask-contrib/dask-sql/actions/runs/1660208403) and looks like things are working again 🎉 thanks for the work here @ayushdg!
