### ISSUE TITLE
[ENH] Backend agnostic machine learning models 

### ISSUE THREAD

**Issue by VibhuJawa** [dask-contrib/dask-sql#370]
**Is your feature request related to a problem? Please describe.**
As we are working becoming more backend agnostic (GPU/CPU) , we should look into a way of supporting multiple ML backends with minimal code change .

**Describe the solution you'd like**

We currently have to specify the cuml/sklearn model class.  We should look into a way of training models where we detect what the input type is and have the user just specify ‘RandomForest’ and have dask-sql handle inferring the rest of the classname. 

So if the training dataframe is on CPU we use `sklearn` and if it is on GPU we use `cuML`.

**Comment by sarahyurick** [comment]
Now that we are moving away from Dask-ML, we can also look further into doing this.

@randerzander
