### ISSUE TITLE
DASK SQL <-> Spark Coalesce

### ISSUE THREAD

**Issue by beaver3** [dask-contrib/dask-sql#395]
**Is your feature request related to a problem? Please describe.**
I wish I could use dask-sql to do the equivalent of Spark coalesce function:
https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.functions.coalesce.html

```select coalesce(col1,colb) as VALUE_NOT_NULL from TABLE```

**Describe the solution you'd like**

What is the equivalent in Dask SQL to this Code Snippet from Spark?

```
cDf = spark.createDataFrame([(None, None), (1, None), (None, 2)], ("a", "b"))
cDf.show()
+----+----+
|   a|   b|
+----+----+
|null|null|
|   1|null|
|null|   2|
+----+----+

cDf.select(coalesce(cDf["a"], cDf["b"])).show()
+--------------+
|coalesce(a, b)|
+--------------+
|          null|
|             1|
|             2|
+--------------+

cDf.select('*', coalesce(cDf["a"], lit(0.0))).show()
+----+----+----------------+
|   a|   b|coalesce(a, 0.0)|
+----+----+----------------+
|null|null|             0.0|
|   1|null|             1.0|
|null|   2|             0.0|
+----+----+----------------+
```

**Describe alternatives you've considered**
- Using temporary tables and joins 

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by beckernick** [comment]
Perhaps relevant for the GPU side: https://github.com/rapidsai/cudf/issues/10180

**Comment by beaver3** [comment]
yes Iabsolutely: https://github.com/rapidsai/cudf/issues/6759 is also asking for coalesce in dask sql.

**Comment by beaver3** [comment]
this works for me, many thanks!
