### ISSUE TITLE
[ENH]Warn users when training non dask friendly ML models with wrap_predict=False. 

### ISSUE THREAD

**Issue by VibhuJawa** [dask-contrib/dask-sql#417]
**Is your feature request related to a problem? Please describe.**

We should warn users when training non dask friendly ML models with wrap_predict=False.  This is because when `wrap_predict=False` we assume that the model can handle non dask objects. 

https://github.com/dask-contrib/dask-sql/blob/98c38cfba0ca3a08f539523c6480cc2736b505cd/dask_sql/physical/rel/custom/create_model.py#L189-L190

This is often not true for various model classes like `xgboost.XGBRegressor`

**Describe the solution you'd like**
We should create loud warnings based on the model class as the models that can handle dask often have `dask` so if we dont detect that we should potentially wan users. 

CC: @randerzander

**Comment by sarahyurick** [comment]
Any way that this can be integrated with the logic from https://github.com/dask-contrib/dask-sql/pull/926? Is this saying that we should default to `wrap_predict=True` for XGBoost, LightGBM, etc. models?
