### ISSUE TITLE
[DF] Port Sort logic to Datafusion

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#461]
**Is your feature request related to a problem? Please describe.**
Update all existing "Sort" logic to replace Apache Calcite data structures with Apache Datafusion data structures.

**Describe the solution you'd like**
Replace instances of [Calcite LogicalSort](https://calcite.apache.org/javadocAggregate/org/apache/calcite/rel/logical/LogicalSort.html) with correlating instances of [Datafusion Sort](https://docs.rs/datafusion/latest/datafusion/logical_plan/plan/struct.Sort.html). This includes any base classes, functions, members that might also rely on that logic.

**Describe alternatives you've considered**
None

**Additional context**
Success criteria is for all pytests in `test_sort.py` to be passing

**Comment by ayushdg** [comment]
Closed via #505
