### ISSUE TITLE
[DF] Port Filter logic to Datafusion

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#463]
**Is your feature request related to a problem? Please describe.**
Update all existing "Filter" logic to replace Apache Calcite data structures with Apache Datafusion data structures.

**Describe the solution you'd like**
Replace instances of Calcite [LogicalFilter](https://calcite.apache.org/javadocAggregate/org/apache/calcite/rel/logical/LogicalFilter.html) with correlating instances of Datafusion [Filter](https://docs.rs/datafusion/latest/datafusion/logical_plan/plan/struct.Filter.html). This includes any base classes, functions, members that might also rely on that logic.

**Describe alternatives you've considered**
None

**Additional context**
Success criteria is for all pytests in test_filter.py to be passing

**Comment by ChrisJar** [comment]
I can take care of this one

**Comment by jdye64** [comment]
Closed with PR #581
