### ISSUE TITLE
[DF] Port Aggregate logic to Datafusion

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#464]
**Is your feature request related to a problem? Please describe.**
Update all existing "Aggregate" logic to replace Apache Calcite data structures with Apache Datafusion data structures.

**Describe the solution you'd like**
Replace instances of Calcite [LogicalAggregate](https://calcite.apache.org/javadocAggregate/org/apache/calcite/rel/logical/LogicalAggregate.html) with correlating instances of Datafusion [Aggregate](https://docs.rs/datafusion/latest/datafusion/logical_plan/plan/struct.Aggregate.html). This includes any base classes, functions, members that might also rely on that logic.

**Describe alternatives you've considered**
None

**Additional context**
Success criteria is for all pytests in test_groupby.py to be passing

**Comment by charlesbluca** [comment]
Closed with #471
