### ISSUE TITLE
[DF] Port Window logic to Datafusion

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#466]
**Is your feature request related to a problem? Please describe.**
Update all existing "Window" logic to replace Apache Calcite data structures with Apache Datafusion data structures.

**Describe the solution you'd like**
Replace instances of Calcite [LogicalWindow](https://calcite.apache.org/javadocAggregate/org/apache/calcite/rel/logical/LogicalWindow.html) with correlating instances of Datafusion [Window](https://docs.rs/datafusion/latest/datafusion/logical_plan/plan/struct.Window.html). This includes any base classes, functions, members that might also rely on that logic.

**Describe alternatives you've considered**
None

**Additional context**
Success criteria is for all pytests in test_over.py to be passing

**Comment by ayushdg** [comment]
Closed via #545
