### ISSUE TITLE
[DF] Port Union logic to Datafusion

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#470]
**Is your feature request related to a problem? Please describe.**
Update all existing "Union" logic to replace Apache Calcite data structures with Apache Datafusion data structures.

**Describe the solution you'd like**
Replace instances of Calcite [LogicalUnion](https://calcite.apache.org/javadocAggregate/org/apache/calcite/rel/logical/LogicalUnion.html) with correlating instances of Datafusion [Union](https://docs.rs/datafusion/latest/datafusion/logical_plan/plan/struct.Union.html). This includes any base classes, functions, members that might also rely on that logic.

**Describe alternatives you've considered**
None

**Additional context**
Success criteria is for all pytests in test_union.py to be passing

**Comment by galipremsagar** [comment]
Resolved by #542 & #559
