### ISSUE TITLE
[DF] Add GitHub workflow for cargo fmt and cargo clippy

### ISSUE THREAD

**Issue by andygrove** [dask-contrib/dask-sql#472]
**Is your feature request related to a problem? Please describe.**
It is standard practice to have CI run `cargo fmt --check` and `cargo clippy` on pull requests on Rust projects. It makes it easier for other developers to contribute if we are all using the same code formatting.

**Describe the solution you'd like**
Set up GtiHub actions to run `cargo fmt` and `cargo clippy` checks. We can look at the [DataFusion Rust workflow](https://github.com/apache/arrow-datafusion/blob/master/.github/workflows/rust.yml) as an example.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by charlesbluca** [comment]
Closed with #471
