### ISSUE TITLE
[BUG] NameError from DataFusion changes

### ISSUE THREAD

**Issue by DaceT** [dask-contrib/dask-sql#475]
**What happened**:
I'm getting a NameError while testing one of the converted dask-sql notebooks, specifically the `dsql_vs_pyspark_netflow`, with Jeremy's DataFusion changes.

**What you expected to happen**:
I expected it to run with no errors.

**Traceback**:
https://gist.github.com/DaceT/b82b36a092d83ec19f995ce7f9b2e0c7

**Comment by jdye64** [comment]
Looks like I inadvertently changed the build to not include the `sql.yaml` file as I was adding the rust logic. I have made the adjustment and the file will now be present after [this](https://github.com/dask-contrib/dask-sql/pull/471) is merged

**Comment by charlesbluca** [comment]
Closed with #471
