### ISSUE TITLE
[BUG] FileNotFoundError from DataFusion changes

### ISSUE THREAD

**Issue by DaceT** [dask-contrib/dask-sql#477]
**What happened**:
I'm getting a FileNotFoundError  while testing the other converted dask-sql notebooks, `federated_query_demo_dasksql` and `getting_started_with_dasksql`, with Jeremy's DataFusion changes.

**What you expected to happen**:
I expected it to run with no errors.

**Traceback**:
https://gist.github.com/DaceT/9a5c7b406f6c8cbc2b1e181e84114dfb

https://gist.github.com/DaceT/a9a68b03b36eaa447fb368db56c6b128

**Comment by charlesbluca** [comment]
Looking at the traces, it looks like the issue here is the same as in #475, in that the `sql.yaml` is not yet included in the DataFusion build, which should be resolved with #471.

Do you mind if I close this in favor of #475?

**Comment by DaceT** [comment]
I'll close it!
