### ISSUE TITLE
[DF] Build against master branch of DataFusion

### ISSUE THREAD

**Issue by andygrove** [dask-contrib/dask-sql#478]
**Is your feature request related to a problem? Please describe.**
The master branch of DataFusion has bug fixes and new features that we want to use from dask-sql so we may want to build against the master branch in the short term rather than depending on version 7.0.0.

**Describe the solution you'd like**
Change cargo.toml dependency:

``` toml
datafusion = { git="https://github.com/apache/arrow-datafusion/" }
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by charlesbluca** [comment]
Closed with #471
