### ISSUE TITLE
[DF] Support in SQL `EXPLAIN`

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#506]
**Is your feature request related to a problem? Please describe.**
While Dask-SQL supports using `Context.explain(..)` to get the query explain plan we need to support allowing for `EXPLAIN SELECT * FROM TEST` queries so that the explain can happen in the query iteself.

**Describe the solution you'd like**
Allow `EXPLAIN` via the SQL string provided by the user.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ayushdg** [comment]
Completed in #511
