### ISSUE TITLE
[DF] Update rust version in gpuCI

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#526]
Based on the discussion in https://github.com/dask-contrib/dask-sql/pull/508#pullrequestreview-964023289 we should add the argument for the rust version in our gpuci scrips.

**Comment by jdye64** [comment]
@ChrisJar you comfortable tackling this one?

**Comment by ChrisJar** [comment]
Yep!

**Comment by jdye64** [comment]
You are my hero

**Comment by charlesbluca** [comment]
This should be resolved with https://github.com/rapidsai/dask-build-environment/pull/38
