### ISSUE TITLE
[DF] Project step creates additional columns in cases where it may not be needed

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#527]
**What happened**: There's additional memory footprint after the project step in some cases that need to be explored further

**What you expected to happen**: No extra columns created in certain cases

**Minimal Complete Verifiable Example**:

```python
c.sql("SELECT a,b from table ORDER by a,b")
```

In the current execution, the plan projects and gets df.a and df.b from table but creates two new columns that map to the same values even though it's a reference. 
During the sort phase of the execution, we effectively persist a dataframe with 4 columns instead of 2.

**Anything else we need to know?**: This was introduced during the datafusion port since the earlier calcite plan for a similar query didn't have a project phase for the same query and no additional columns were created

**Comment by jdye64** [comment]
I'll take this. I think I know right where this is happening and why. I remember early on we didn't have RexType operators for `references` and therefore this was probably overlooked. Now that we do have reference types a check could be introduced to check for this and not create the new temporary column.

**Comment by ayushdg** [comment]
closed via #644
