### ISSUE TITLE
[DF] EmpyRelation queries cause errors

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#556]
**Is your feature request related to a problem? Please describe.**
Any SQL query not performed against a backing table, Ex: `"SELECT 1 AS a, 1.5 AS b, 'x' AS c`, results in the error `NotImplementedError: No relational conversion for node type EmptyRelation available (yet).`

**Describe the solution you'd like**
Empty backing table queries should be supported.

**Describe alternatives you've considered**
None

**Additional context**
Likely the cleanest way to achieve this is introduce this relation as a `no-op` clause in the `rel/convert.py` logic leading to the `project.py` logic to handle it

**Comment by ChrisJar** [comment]
Happy to work on this!

**Comment by jdye64** [comment]
Closed with PR #611
