### ISSUE TITLE
[BUG] Column name selection gives incorrect result

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#569]
**What happened**:
Selecting a specific column from df returns the first column

**What you expected to happen**:
Correct column being returned

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
from dask_sql import Context

df = pd.DataFrame({"a":[1,2,3],"b":[4,5,6]})

c = Context()
c.create_table("df",df)

c.sql("SELECT * from df").compute()

   a  b
0  1  4
1  2  5
2  3  6

c.sql("SELECT b from df").compute()

   b
0  1
1  2
2  3
```

**Anything else we need to know?**:
I think it might have been introduced in #559 but I'm not sure. 
I also wonder why none of the tests caught this. 

**Environment**:

- dask-sql version: datafusion-sql-planner branch with #558 
- Python version: 3.8
- Operating System: ubuntu18.04
- Install method (conda, pip, source): pip

**Comment by galipremsagar** [comment]
On the `datafusion-sql-planner` branch with latest changes, I don't seem to run into this issue:
```python
>>> import pandas as pd
df = pd.DataFrame({"a":[1,2,3],"b":[4,5,6]})>>> from dask_sql import Context
>>> 
>>> df = pd.DataFrame({"a":[1,2,3],"b":[4,5,6]})
>>> c = Context()
>>> c.create_table("df",df)
>>> c.sql("SELECT * from df").compute()
   a  b
0  1  4
1  2  5
2  3  6
>>> c.sql("SELECT b from df").compute()
   b
0  4
1  5
2  6
```

@ayushdg could you check if you have an outdated branch?

**Comment by randerzander** [comment]
@galipremsagar this is w/ #558

**Comment by ayushdg** [comment]
Can confirm that this is with #558 and doesn't show up when setting `sql.optimize:False`

**Comment by galipremsagar** [comment]
Ah, Thanks @randerzander. It would then be easier for @jdye64 to know if some behavior is changing because of https://github.com/dask-contrib/dask-sql/pull/558

**Comment by jdye64** [comment]
Hmm interesting. Will try to take a look at this today. Thanks for pointing it out. Nothing obvious jumps out to me what could be causing it.

**Comment by jdye64** [comment]
#571 resolved this.
