### ISSUE TITLE
[DF] DataFusion optimizer enhancements

### ISSUE THREAD

**Issue by andygrove** [dask-contrib/dask-sql#582]
**Is your feature request related to a problem? Please describe.**
This issue is to track optimization rules that we would like to add to DataFusion to improve benchmark results.

- [x] https://github.com/apache/arrow-datafusion/issues/2739

**Describe the solution you'd like**
Implement these rules.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jdye64** [comment]
Wanted to note here that I opened issue https://github.com/dask-contrib/dask-sql/issues/587 before seeing this issue and there is a PR present.

**Comment by jdye64** [comment]
Closed with #588
