### ISSUE TITLE
[DF] Add ATAN2() function

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#619]
**Is your feature request related to a problem? Please describe.**
DataFusion does not support the `ATAN2` function out of the box so we need to register it as a custom function for Dask-SQL

**Describe the solution you'd like**
Add the `ATAN2` function to `DaskSQLContext` and create the appropriate bindings

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sarahyurick** [comment]
Can be closed.
