### ISSUE TITLE
[DF] Add `COT` math function

### ISSUE THREAD

**Issue by jdye64** [dask-contrib/dask-sql#621]
**Is your feature request related to a problem? Please describe.**
Cotangent function is not supported out of the box with DataFusion. Register a `COT` math function and provide all bindings.

**Describe the solution you'd like**
Register a function in `DaskSQLContext` for `COT` that calculates cotangent

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sarahyurick** [comment]
Can be closed, thanks!

**Comment by ayushdg** [comment]
closed via #657
