### ISSUE TITLE
[DF] Importing Context attempts to load server components

### ISSUE THREAD

**Issue by randerzander** [dask-contrib/dask-sql#678]
I've just built the datafusion-sql-planner branch from source in a fairly stripped down conda environment.

On trying to: `from dask_sql import Context`, I got errors about missing uvicorn:
```
>>> from dask_sql import Context
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/studio-lab-user/.conda/envs/dsql/lib/python3.9/site-packages/dask_sql/__init__.py", line 6, in <module>
    from .server.app import run_server
  File "/home/studio-lab-user/.conda/envs/dsql/lib/python3.9/site-packages/dask_sql/server/app.py", line 7, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
>>> 
```

Surprisingly, this is from the server code. Does it seem like something's wrong with my build, or is it expected to load Dask-SQL server code when trying to create a Context?

**Comment by charlesbluca** [comment]
Looks like something might be wrong in your build here - I'm seeing `uvicorn` listed as a dependency both in our setup file and conda recipes.

I will note that thinking about how to wrap imports like this conditionally is definitely part of the work that would go into separating the server out into an optional component of the packages, xref #435

**Comment by randerzander** [comment]
For future reference to others, `python setup.py install` wont complain about missing dependencies.

`conda install -c conda-forge uvicorn fastapi` fixed this issue for me.
