### ISSUE TITLE
[DF] Remaining DataFusion / sqlparser work for the GA release

### ISSUE THREAD

**Issue by andygrove** [dask-contrib/dask-sql#706]
**Is your feature request related to a problem? Please describe.**
I really need one place to track all of the work that needs to happen in the dependencies.

## sqlparser

- [x] https://github.com/sqlparser-rs/sqlparser-rs/pull/581
- [x] https://github.com/sqlparser-rs/sqlparser-rs/issues/593
- [x] https://github.com/sqlparser-rs/sqlparser-rs/pull/585
- [x] Release sqlparser 0.22

## DataFusion

- [ ] https://github.com/apache/arrow-datafusion/pull/3101
- [x] https://github.com/apache/arrow-datafusion/pull/3208
- [x] https://github.com/apache/arrow-datafusion/pull/3235
- [x] https://github.com/apache/arrow-datafusion/pull/3246
- [ ] Review / improve type coercion & validation logic by implementing as optimizer rule(s)
  - [x] https://github.com/apache/arrow-datafusion/pull/3222
  - [x] https://github.com/apache/arrow-datafusion/pull/3254
  - [x] https://github.com/apache/arrow-datafusion/pull/3328
  - [x] https://github.com/apache/arrow-datafusion/issues/3269
  - [x] IS TRUE/FALSE/UNKNOWN - https://github.com/apache/arrow-datafusion/issues/3268
  - [ ] Case when ([test](https://github.com/dask-contrib/dask-sql/blob/datafusion-sql-planner/tests/integration/test_rex.py#L24))
  - [ ] Integer division ([test](https://github.com/dask-contrib/dask-sql/blob/datafusion-sql-planner/tests/integration/test_rex.py#L428))
- [x] https://github.com/apache/arrow-datafusion/issues/2883
- [ ] overlay operator (parsing error) (postgresql syntax https://www.postgresql.org/docs/9.1/functions-string.html)  
- [ ] datetime ops ([test](https://github.com/dask-contrib/dask-sql/blob/datafusion-sql-planner/tests/integration/test_rex.py#L538))
- [x] https://github.com/apache/arrow-datafusion/issues/3097
- [ ] https://github.com/apache/arrow-datafusion/issues/3390
- [ ] https://github.com/apache/arrow-datafusion/issues/3408
- [x] https://github.com/apache/arrow-datafusion/issues/3409

## Stretch Goals (nice to have but can wait until next release)

- [ ] position (`POSITION('a' IN a FROM 4)`) (non standard sql syntax)

**Comment by isidentical** [comment]
@andygrove does that make sense to also include #705 (or apache/arrow-datafusion/issues/3195) in here as well?

**Comment by andygrove** [comment]
> @andygrove does that make sense to also include #705 (or [apache/arrow-datafusion/issues/3195](https://github.com/apache/arrow-datafusion/issues/3195)) in here as well?

Yes, it does. Thanks for that. Feel free to add to the list above as there is a good chance I am not aware of all the issues, as in this case.

**Comment by andygrove** [comment]
I think we can close this now. I did move some items to a new issue - https://github.com/dask-contrib/dask-sql/issues/822
