### ISSUE TITLE
[ENH] Optimizer rule to drop join key columns post join

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#898]
**Is your feature request related to a problem? Please describe.**
Many queries follow a pattern where certain columns are only used as join keys and aren't really needed/selected in the query post join. In cases such as these it might be useful to be able to drop those columns post join rather than carrying them around for subsequent ops and only dropping them at the end during the projection.

**Describe the solution you'd like**
Add an optimizer rule that either adds a projection step post join or adds some sort of column filter post join to only keep the needed columns. 

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

Here are some example cases which showcase the issue:

```python
print(c.explain("SELECT SUM(df.a),df2.b FROM df INNER JOIN df2 ON df.c=df2.c GROUP BY df2.b"))
Projection: SUM(df.a), df2.b
  Aggregate: groupBy=[[df2.b]], aggr=[[SUM(df.a)]]
    Inner Join: df.c = df2.c
      Filter: df.c IS NOT NULL
        TableScan: df projection=[a, c], partial_filters=[df.c IS NOT NULL]
      Filter: df2.c IS NOT NULL
        TableScan: df2 projection=[b, c], partial_filters=[df2.c IS NOT NULL]
```
Here we carry `column c` into the aggregate step even though it can be dropped

**Comment by sarahyurick** [comment]
Is anyone currently working on this? If not, I'd be happy to start looking into it!
