### ISSUE TITLE
[Improvement] Reduce test_ml_experiment test time

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#970]
**What happened**:
Locally when running pytests, I've observed the `test_ml_experiment` within `test_model` to be significantly slower than the other tests.
Here's a breakdown of the slowest 5 tests on my local system:
```
271.66s call     tests/integration/test_model.py::test_ml_experiment
8.77s call     tests/integration/test_model.py::test_experiment_automl_classifier
7.61s call     tests/integration/test_model.py::test_experiment_automl_regressor
5.03s call     tests/integration/test_cmd.py::test_meta_commands
4.37s call     tests/integration/test_model.py::test_mlflow_export_xgboost
```

**Comment by ayushdg** [comment]
On further inspection it looks like this test hasn't changed much apart from changing dask_ml grid search cv to scikit learn grid search cv, but the runtime has gone from ~26s -> ~150-200s. Probably worth investigating further

**Comment by sarahyurick** [comment]
Yeah, I'm able to reproduce this time difference. From your suggestion, one solution could be to migrate some of Dask-ML's search classes into Dask-SQL, such as `GridSearchCV`, `RandomizedSearchCV`, etc. See the full list [here](https://github.com/dask/dask-ml/blob/80eb0d81b22df3762706384c3ca1c0be4137e591/dask_ml/model_selection/__init__.py).

Depending on how many classes we want to transfer, this could add a significant amount of code, for example [dask-ml/_search.py](https://github.com/dask/dask-ml/blob/7b8c8e0f2d3fb029850e9bf07203b8f7176bdf3e/dask_ml/model_selection/_search.py) (which only includes `GridSearchCV` and `RandomizedSearchCV`) is over 1000 lines of code.

I'd be happy to discuss this on a call as well.

**Comment by ayushdg** [comment]
cc: @VibhuJawa In case you have any opinions on the issue. It looks like dask_ml's gridSearchCV performs better than the sklearn equivalent even when using `n_jobs=-1`.

**Comment by VibhuJawa** [comment]
> cc: @VibhuJawa In case you have any opinions on the issue. It looks like dask_ml's gridSearchCV performs better than the sklearn equivalent even when using `n_jobs=-1`.

Hmm, That is interesting and kind of in conflict to what @ChrisJar had found  . We may want to investigate on what is  happening here.

**Comment by sarahyurick** [comment]
Just opened https://github.com/dask-contrib/dask-sql/pull/1007 to resolve this issue, and just want to make sure that others can reproduce the runtimes reported there.

After discussing with @randerzander, it doesn't seem worth it to add any significant amounts of code since the slowdown is due to using scikit-learn over Dask-ML, and doesn't appear to be due to any deprecations on the Dask-SQL side. Plus, Dask-ML's `GridSearchCV` is still compatible with Dask-SQL if a user is interested in using it over the scikit-learn version.

Does this sound reasonable?
