### ISSUE TITLE
[ENH] Collect and track table statistics when applicable

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#994]
**Is your feature request related to a problem? Please describe.**
When creating tables that were read from parquet files, dask-sql can also collect and keep partition wise statistics that can be used downstream for future optimizations (like join reordering, or a heuristics to decide on physical plan paths like join algorithms)

**Describe the solution you'd like**
- [x] Add a utility to dask-sql that has the ability to return partition wise statistics (wip #999)
- [ ] Update DataContainer to hold these stats (and populate them if applicable) after table creation (or table_scan)
- [ ] Update provide these stats to `DaskTable` and make it accessible via rust (for optimizer rules) 

**Additional context**
Required for the implementation of #950 

Initially the scope of this can be for parquet files only and can be expanded in the future to other file types.

**Comment by sarahyurick** [comment]
Will be exploring this as I work on https://github.com/dask-contrib/dask-sql/pull/1027

**Comment by sarahyurick** [comment]
Related to https://github.com/dask-contrib/dask-sql/issues/851
